version: "3.9"

services:
  frontend:
    build: ./client
    container_name: tikeft-frontend
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm run build"

  backend:
    build: ./server
    container_name: tikeft-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    command: sh -c "npm install && npm start"

  nginx:
    image: nginx:alpine
    container_name: tikeft-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
