version: "3.8"

services:
  tikeft-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tikeft-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=4000
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme}
    volumes:
      - ./server/contacts.json:/app/server/contacts.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tikeft.rule=Host(`tikeft.com`)"
      - "traefik.http.routers.tikeft.entrypoints=websecure"
      - "traefik.http.routers.tikeft.tls.certresolver=letsencrypt"
      - "traefik.http.services.tikeft.loadbalancer.server.port=4000"
