version: "3.8"

services:
  frontend:
    build:
      context: ./client
    container_name: tikeft_frontend
    restart: always
    ports:
      - "3000:3000" # for debugging locally, not needed in production
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./server
    container_name: tikeft_backend
    restart: always
    expose:
      - "4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    command: ["npm", "run", "start"] # adjust if you use yarn or custom script

  nginx:
    image: nginx:alpine
    container_name: tikeft_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
